### Create Company User
POST http://localhost:3000/api/company/register
Content-Type: application/json

{
  "username": "danezidane",
  "password": "123qasw123",
  "confirm_password": "123qasw123",
  "email": "danezidane@example.com",
  "company_name": "Zidane Company",
  "no_handphone": "081234567890",
  "province": "Jawa Timur",
  "city": "Surabaya",
  "address": "Jl. Zidane No. 123",
  "about_company": "Company about Zidane"
}


### Login Company
POST http://localhost:3000/api/company/login
Content-Type: application/json

{
  "username": "danezidane",
  "password": "123qasw123"
}

### Create Employee
POST http://localhost:3000/api/company/27139b9a-0bdb-440d-848d-36dd3ea725cb/employee/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YjdkOTdmLWQ1MjMtNGI3YS04Y2NmLWYwMWU4MTg3ODU5OSIsImNvbXBhbnlfaWQiOiIyNzEzOWI5YS0wYmRiLTQ0MGQtODQ4ZC0zNmRkM2VhNzI1Y2IiLCJpYXQiOjE3NjQ0MjA5NzEsImV4cCI6MTc2NDUwNzM3MX0.oacDZqrlhP04Kxl9iUNXpQnb_GhvMzvPxATUdVnxkXM
Content-Type: application/json

{
  "NIK": "123474872843948912",
  "nama": "zidane 1",
  "kode_divisi": 1,
  "kode_jabatan": 1
}

### Update Employee
POST http://localhost:3000/api/employee/68dccf14-539d-4345-99b3-eb102e8a003e/update
Content-Type: application/json

{
  "NIK": "123474837472843948",
  "nama": "zidane abbas mallaniung",
  "kode_divisi": 3,
  "kode_jabatan": 2,
  "id_perusahaan": "d861b022-bbcc-480e-b1cc-c6650900eda6"
}

### get employees
GET http://localhost:3000/api/company/27139b9a-0bdb-440d-848d-36dd3ea725cb/employee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YjdkOTdmLWQ1MjMtNGI3YS04Y2NmLWYwMWU4MTg3ODU5OSIsImNvbXBhbnlfaWQiOiIyNzEzOWI5YS0wYmRiLTQ0MGQtODQ4ZC0zNmRkM2VhNzI1Y2IiLCJpYXQiOjE3NjQ0MjA5NzEsImV4cCI6MTc2NDUwNzM3MX0.oacDZqrlhP04Kxl9iUNXpQnb_GhvMzvPxATUdVnxkXM

### delete employee
DELETE http://localhost:3000/api/employee/68dccf14-539d-4345-99b3-eb102e8a003e

### get detail employee
GET http://localhost:3000/api/employee/9289cd94-15f0-47e5-9498-ee79666d63a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YjdkOTdmLWQ1MjMtNGI3YS04Y2NmLWYwMWU4MTg3ODU5OSIsImNvbXBhbnlfaWQiOiIyNzEzOWI5YS0wYmRiLTQ0MGQtODQ4ZC0zNmRkM2VhNzI1Y2IiLCJpYXQiOjE3NjQ0MjA5NzEsImV4cCI6MTc2NDUwNzM3MX0.oacDZqrlhP04Kxl9iUNXpQnb_GhvMzvPxATUdVnxkXM

### PUT employee
PUT http://localhost:3000/api/employee/9289cd94-15f0-47e5-9498-ee79666d63a2/update
Content-Type: application/json

{
  "NIK": "123474837472843948",
  "nama": "zidane abbas mallaniung",
  "kode_divisi": 3,
  "kode_jabatan": 2,
  "id_perusahaan": "d861b022-bbcc-480e-b1cc-c6650900eda6"
}



### create position
POST http://localhost:3000/api/company/27139b9a-0bdb-440d-848d-36dd3ea725cb/position/create
Content-Type: application/json

{
  "nama" : "position 2"
}

### update position
PUT http://localhost:3000/api/company/27139b9a-0bdb-440d-848d-36dd3ea725cb/position/3/update
Content-Type: application/json

{
  "nama" : "position 10"
}

### get position
GET http://localhost:3000/api/company/cc04736c-53f1-42ee-96b4-04d90719c8f9/position

### delete position
DELETE http://localhost:3000/api/company/63ca91ed-5a90-4e81-a958-bd3cd15df5c6/position/1


### create division
POST http://localhost:3000/api/company/27139b9a-0bdb-440d-848d-36dd3ea725cb/division/create
Content-Type: application/json

{
  "nama" : "division 3"
}

###update division
PUT http://localhost:3000/api/company/d4450904-8111-41df-98c7-46e6336e0899/division/2/update
Content-Type: application/json

{
  "nama" : "division 100"
}

### get division
GET http://localhost:3000/api/company/63ca91ed-5a90-4e81-a958-bd3cd15df5c6/division

### delete division
DELETE http://localhost:3000/api/company/63ca91ed-5a90-4e81-a958-bd3cd15df5c6/division/1







